### ISSUE TITLE
`Bug`: API User or API Token are mutually exclusive

### ISSUE THREAD

**Issue by gyptazy** [gyptazy/ProxLB#142]
## General
Within the configuration you can configure user/pass or token authorization. However, if both is defined - user/pass is preferred, even the password field is empty or tokens are defined.

```
proxmox_api:
  hosts: ['virt01.example.com', '10.10.10.10', 'fe01::bad:code::cafe']
  user: root@pam
  pass: crazyPassw0rd!
  token_id: proxlb
  token_secret: 430e308f-1337-1337-beef-1337beefcafe
```

ProxLB should validate if `user` and `token_id` are defined and throw an error before the API rejects the authentication duo to wrong credentials.

## Weighting
Score: 3

## Config
```
proxmox_api:
  hosts: ['virt01.example.com', '10.10.10.10', 'fe01::bad:code::cafe']
  user: root@pam
  pass: crazyPassw0rd!
  token_id: proxlb
  token_secret: 430e308f-1337-1337-beef-1337beefcafe
```

## Meta

Version: 1.1.0a
Installed from: any
Running as: any
