### ISSUE TITLE
`Feature`: Change schedule to hours or minutes

### ISSUE THREAD

**Issue by laitco** [gyptazy/ProxLB#168]
## General
Change schedule to hours/minutes like 12h/720m to be able to configure smaller runtimes than 1 hour.

## Details
Actual: 12
Syntax should be: 12h or 720m

**Comment by laitco** [comment]
Hi @gyptazy,

second one looks fine to me with formats: hours, minutes, seconds 👍 

Regards,
laitco

**Comment by gyptazy** [comment]
Will be part of release 1.1.1:

You can now define the schedule in minutes or hours:
```
service:
  daemon: False
  schedule:
    interval: 12
    format: hours
  log_level: INFO
```

Info: Breaking change - requires users to update their configs.
