### ISSUE TITLE
Feature: host groups

### ISSUE THREAD

**Issue by antitbone** [gyptazy/ProxLB#65]
Hello

Is it planned to implement cluster management on multiple computer rooms?

It would be interesting to be able to define host groups and limit the migration of VMs to host groups.
This will allow the distribution of vms over several computer rooms so that the hosted services can withstand the loss of a room.
And have a degraded mode in which host groups are not respected if one of the host groups is not available.

Example with a ceph stretch cluster on Two computer rooms + a witness. Only the compute is to be migrated
If the cluster is correctly sized it is possible to survive the loss of a computer room.

Antoine

**Comment by gyptazy** [comment]
Hey @antitbone,

thanks for your input. When I initially integrated the affinity / anti-affinity rules I also thought about something like that. However, it's not really possible to do it in a user friendly way. While we have tags for VMs, we only have notes fields for nodes. This means, this could be abused in a dirty way, or something like an additional matrix in YAML or JSON could be provided which might look like:

```
group1:
  nodes:
    - node01
    - node02
    - node03
  vms:
    - vm01
    - vm02
    - vm03
group2:
  nodes:
    - node04
    - node05
    - node06
  vms:
    - vm04
    - vm05
    - vm06
```

or

```
{
  "group1": {
    "nodes": [
      "node01",
      "node02",
      "node03"
    ],
    "vms": [
      "vm01",
      "vm02",
      "vm03"
    ]
  },
  "group2": {
    "nodes": [
      "node04",
      "node05",
      "node06"
    ],
    "vms": [
      "vm04",
      "vm05",
      "vm06"
    ]
  }
}
```

So, from a technical perspective this isn't difficult but I'm not sure which way could be the best one for a user to provide the information / matrix. Happy to hear feedback!

Cheers,
gyptazy

**Comment by antitbone** [comment]
It does not seem possible to have tags at the host level in proxmox.
Host groups in an external file make sense.
Especially since the topology of the hosts moves little in time.

```
group1:
  nodes:
    - node01
    - node02
    - node03
group2:
  nodes:
    - node04
    - node05
    - node06
```


But the assignment of vm to a group could be done by a tag.
ex: pbl_group-preferred_group1, pbl_group-exclusive_group1

Antoine
